// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2025-2026 Lazy Devs

package com.lazydevs.wristotle.help

/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Regenerate via:
 *   tools/sync_features.sh                  # pull data/features.json from docs
 *   python3 tools/regenerate_help_timeline.py
 *
 * Canonical source: wristotle-docs/data/features.json.
 * Style guide for new entries: HelpContent.kt's file-level KDoc.
 */
internal object HelpTimeline {
    val timeline: List<FeatureEntry> = listOf(
        FeatureEntry(
            id = "v1-11-0-bbl-cricket",
            date = "2026-06-14",
            companionVersion = "v1.11.0",
            watchVersion = null,
            title = "Cricket adds the Big Bash League",
            description = "Cricket now covers Australia's Big Bash League — ask for BBL standings or whether your team won.",
            sampleQuery = "BBL standings",
            docsPath = "voice-commands/#sports",
        ),
        FeatureEntry(
            id = "v1-11-0-update-sports-data",
            date = "2026-06-14",
            companionVersion = "v1.11.0",
            watchVersion = null,
            title = "Sports data updates itself — or on demand",
            description = "Sports leagues and teams now refresh automatically, and Settings → Sports has an Update sports data button to pull the latest now.",
            sampleQuery = null,
            docsPath = "voice-commands/#sports",
        ),
        FeatureEntry(
            id = "v1-10-2-speak-sports",
            date = "2026-06-14",
            companionVersion = "v1.10.2",
            watchVersion = null,
            title = "Speak sports replies on your watch",
            description = "Sports answers can now be read aloud on your watch — there's a new Sports toggle under Settings → Speech.",
            sampleQuery = "who won the last race",
            docsPath = "voice-commands/#sports",
        ),
        FeatureEntry(
            id = "v1-10-1-f1-sessions",
            date = "2026-06-14",
            companionVersion = "v1.10.1",
            watchVersion = null,
            title = "Formula 1 qualifying, sprint and pole results",
            description = "Ask Formula 1 for qualifying, sprint, or pole results, and every race answer now shows which session it's from.",
            sampleQuery = "who won the last f1 qualifying",
            docsPath = "voice-commands/#sports",
        ),
        FeatureEntry(
            id = "v1-10-0-sports-phase-2",
            date = "2026-06-14",
            companionVersion = "v1.10.0",
            watchVersion = null,
            title = "Formula 1 and cricket, plus per-sport on/off",
            description = "Sports adds Formula 1 (races + driver/constructor standings) and cricket (IPL, World Cup), and lets you switch off sports you don't follow in Settings → Sports.",
            sampleQuery = "when is the next f1 race",
            docsPath = "voice-commands/#sports",
        ),
        FeatureEntry(
            id = "v1-9-0-sports",
            date = "2026-06-14",
            companionVersion = "v1.9.0",
            watchVersion = null,
            title = "Sports scores, schedules, and standings",
            description = "Ask any team's next game, last result, live score, or league standings — across soccer, the NBA, NFL, MLB, and NHL.",
            sampleQuery = "when do the warriors play next",
            docsPath = "voice-commands/#sports",
        ),
        FeatureEntry(
            id = "v1-8-0-stats",
            date = "2026-06-11",
            companionVersion = "v1.8.0",
            watchVersion = null,
            title = "On-device activity stats page",
            description = "Settings → 📊 Stats surfaces top intents, active hours, accuracy, and where Wristotle stumbles — all computed on-device.",
            sampleQuery = null,
            docsPath = "voice-commands/#on-device-stats",
        ),
        FeatureEntry(
            id = "v1-7-2-alarm-time-fixes",
            date = "2026-06-11",
            companionVersion = "v1.7.2",
            watchVersion = null,
            title = "SetAlarm accepts compound durations + dotted AM/PM",
            description = "\"Set an alarm for one hour and four minutes from now\" now sets an alarm 64 minutes ahead instead of erroring (closes #12). \"Set an alarm for 7:51 p.m.\" parses the same as \"7:51 pm\" — the dots in a.m./p.m. no longer break the time parser. SetTimer + SetAlarm now share one duration-parsing helper so they can't drift apart again.",
            sampleQuery = "set an alarm for one hour and four minutes from now",
            docsPath = "voice-commands/#set-alarm",
        ),
        FeatureEntry(
            id = "v1-7-1-tts-backup",
            date = "2026-06-10",
            companionVersion = "v1.7.1",
            watchVersion = null,
            title = "TTS settings now travel in backups + diagnostics",
            description = "Settings → 🔊 Speech is now included in Backup & Restore — mode, endpoint, voice, model, and per-intent toggles all survive a phone reset. The API key rides only when you tick the secret checkbox (off by default), same as every other key. The Diagnostics bug-report export also captures the TTS provider state (set/empty only — never the key value).",
            sampleQuery = null,
            docsPath = null,
        ),
        FeatureEntry(
            id = "v1-7-0-on-watch-tts",
            date = "2026-06-10",
            companionVersion = "v1.7.0",
            watchVersion = "v1.2.0",
            title = "Speak replies on the watch (experimental)",
            description = "Settings → 🔊 Speech turns voice replies on. Pick which intents speak (Ask Agent / Morning brief / Reminders / Tasks / Notes / Calendar / Lookups / …), pick a TTS engine (Android local, or any OpenAI-compatible /v1/audio/speech endpoint), and test it in the same card. Cloud TTS hits ~1 s time-to-first-audio. Pebble Time 2 + Pebble Round 2 only — every other watch model drops the chunks silently. Off by default.",
            sampleQuery = "ask agent what is the capital of france",
            docsPath = "voice-commands/#speak-on-watch",
        ),
        FeatureEntry(
            id = "v1-6-2-voice-fixes",
            date = "2026-06-09",
            companionVersion = "v1.6.2",
            watchVersion = null,
            title = "Voice fixes — punctuation, word numbers, cancel timer",
            description = "Sent text messages preserve the trailing ? / ! you said. SetTimer / SetAlarm / Reminder all recognise 11-19 and 21-99 as word-form durations (\"set a timer for eleven minutes\"). \"Cancel timer\" now points to the Clock app instead of claiming there's no reminder by that name (#11).",
            sampleQuery = "set a timer for eleven minutes",
            docsPath = "voice-commands/",
        ),
        FeatureEntry(
            id = "v1-6-0-notif-log",
            date = "2026-06-07",
            companionVersion = "v1.6.0",
            watchVersion = null,
            title = "Morning brief catches dismissed notifications (opt-in)",
            description = "Optional persisted log lets the brief include notifications you swiped or cleared earlier today. App id + conversation key + timestamp only — never the body or sender.",
            sampleQuery = "morning brief",
            docsPath = "voice-commands/#morning-brief",
        ),
        FeatureEntry(
            id = "v1-5-0-persistent-reminders",
            date = "2026-06-06",
            companionVersion = "v1.5.0",
            watchVersion = null,
            title = "Persistent reminders — keep nagging until you tap Stop",
            description = "Ask for a \"persistent reminder\" or \"nag me\" and your phone re-fires the reminder every few minutes after the watch pin fires (#10).",
            sampleQuery = "persistent reminder to take meds at nine",
            docsPath = "voice-commands/#persistent-reminders",
        ),
        FeatureEntry(
            id = "v1-4-1-cleartext-http",
            date = "2026-06-06",
            companionVersion = "v1.4.1",
            watchVersion = null,
            title = "Self-hosted endpoints over HTTP work again",
            description = "Ask Agent, STT, and MCP requests to plain http:// URLs (LAN, Tailscale, self-signed) no longer get blocked by Android (#9).",
            sampleQuery = null,
            docsPath = "features/#settings-tab-whats-in-each-category",
        ),
        FeatureEntry(
            id = "v1-4-0-morning-brief",
            date = "2026-06-06",
            companionVersion = "v1.4.0",
            watchVersion = null,
            title = "Morning brief — voice rollup of today's plate",
            description = "One-shot rollup of today's meetings, alarms, reminders, tasks, notes, and unread messages from your messaging apps.",
            sampleQuery = "morning brief",
            docsPath = "voice-commands/#morning-brief",
        ),
        FeatureEntry(
            id = "v1-3-1-alarm-fix-perm-card-fix",
            date = "2026-06-05",
            companionVersion = "v1.3.1",
            watchVersion = null,
            title = "Bug fixes — relative alarms + Permissions tab polish",
            description = "Relative alarms (\"an hour from now\") fire on time again; Voice Input no longer leaves an empty card (#7, #8).",
            sampleQuery = "set an alarm for an hour from now",
            docsPath = "features/#settings-tab-whats-in-each-category",
        ),
        FeatureEntry(
            id = "watch-v1-1-0-color-theme",
            date = "2026-06-05",
            companionVersion = "v1.3.0",
            watchVersion = "v1.1.0",
            title = "Watch polish + opt-in color theme + chat bubbles",
            description = "Per-row icons across every list, rounded chat bubbles, and an opt-in colour theme controlled from the companion (color-capable watches only).",
            sampleQuery = null,
            docsPath = "features/#on-watch-ui",
        ),
        FeatureEntry(
            id = "v1-2-0-folder-sync",
            date = "2026-06-05",
            companionVersion = "v1.2.0",
            watchVersion = null,
            title = "Folder sync for Notes + Conversations",
            description = "Sync Notes and Conversations to any folder on your phone — Obsidian, Joplin, Dropbox, git vault — Markdown by default.",
            sampleQuery = null,
            docsPath = "features/#settings-tab-whats-in-each-category",
        ),
        FeatureEntry(
            id = "v1-1-0-agent-aliases-polish",
            date = "2026-06-05",
            companionVersion = "v1.1.0",
            watchVersion = null,
            title = "Claude web search + smarter aliases + reminder polish",
            description = "Anthropic web-search toggle for Ask Agent, smarter app-alias matching, and cleaner reminder titles (#4).",
            sampleQuery = "ask claude what's the score of today's lakers game",
            docsPath = "features/#settings-tab-whats-in-each-category",
        ),
        FeatureEntry(
            id = "v1-0-4-mcp-card",
            date = "2026-06-04",
            companionVersion = "v1.0.4",
            watchVersion = null,
            title = "MCP server card — edit, enable/disable, scheme guard",
            description = "MCP servers gain in-place edit, an enable/disable toggle, a raw-token scheme-guard warning, and a 401-refresh crash fix.",
            sampleQuery = null,
            docsPath = "features/#settings-tab-whats-in-each-category",
        ),
        FeatureEntry(
            id = "v1-0-0",
            date = "2026-06-04",
            companionVersion = "v1.0.0",
            watchVersion = "v1.0.0",
            title = "Leaving alpha — first-launch setup wizard",
            description = "Leaving alpha. First-launch wizard walks new users through models, permissions, and app scan; persistent Settings → 🌟 Setup card.",
            sampleQuery = null,
            docsPath = "features/#settings-tab-whats-in-each-category",
        ),
        FeatureEntry(
            id = "stt-providers",
            date = "2026-06-03",
            companionVersion = "v0.20.0",
            watchVersion = null,
            title = "Cloud + self-hosted speech-to-text",
            description = "Pick on-device Whisper, any OpenAI-compatible HTTP endpoint, or a primary + fallback pair. \"Test connection\" verifies before first use.",
            sampleQuery = null,
            docsPath = "features/#models-optional",
        ),
        FeatureEntry(
            id = "whisper-import",
            date = "2026-06-03",
            companionVersion = "v0.19.0",
            watchVersion = null,
            title = "Import custom Whisper models",
            description = "Sideload any whisper.cpp .bin from your phone (fine-tuned, language-specific, distilled). Magic bytes validated before copy.",
            sampleQuery = null,
            docsPath = "features/#models-optional",
        ),
        FeatureEntry(
            id = "alarms-v2",
            date = "2026-06-02",
            companionVersion = "v0.18.0",
            watchVersion = "v0.10.0",
            title = "Alarms with phone / watch / both destinations",
            description = "Re-do of the alarm feature. Settings → ⏰ Alarms & Reminders → Alarms — create one-shot alarms via the editor (time + label + destination: Phone / Watch / Both) or by voice (\"set an alarm for 7am\" honours the default-destination dropdown). \"Cancel the alarm\" / \"cancel 7am alarm\" cancels watch alarms; phone alarms still have to be dismissed in the system clock. New BUTTON_ACTION_ALARMS = 4 lets you bind SELECT / long-press UP / long-press DOWN to the on-watch alarm list.",
            sampleQuery = "set an alarm for 7am",
            docsPath = "features/#on-watch-ui",
        ),
        FeatureEntry(
            id = "configurable-chat-buttons",
            date = "2026-06-01",
            companionVersion = "v0.17.0",
            watchVersion = "v0.9.0",
            title = "Configurable chat-surface shortcuts",
            description = "Bind SELECT, long-press UP, and long-press DOWN on the watch chat screen to any of Dictation, Quick menu (chooser), Notes, or Tasks. Defaults keep the existing muscle memory. Edit via Wristotle's gear-icon settings or the companion's Watch settings card.",
            sampleQuery = null,
            docsPath = "features/#on-watch-ui",
        ),
        FeatureEntry(
            id = "help-page",
            date = "2026-06-01",
            companionVersion = "v0.16.2",
            watchVersion = null,
            title = "In-app Help page",
            description = "Settings → ❓ Help. Searchable feature history (newest first), discovery tips, deep-links into the docs. Shows watch versions alongside companion versions for paired releases.",
            sampleQuery = null,
            docsPath = "features/#settings-tab-whats-in-each-category",
        ),
        FeatureEntry(
            id = "custom-ask-agent-triggers",
            date = "2026-06-01",
            companionVersion = "v0.16.0",
            watchVersion = null,
            title = "Custom Ask Agent trigger words",
            description = "Add your own wake words for Ask Agent — works as a verb (\"ask jarvis …\") or bare (\"Jarvis, …\").",
            sampleQuery = "Jarvis, what's the weather?",
            docsPath = "voice-commands/#ask-agent-llm-passthrough",
        ),
        FeatureEntry(
            id = "whisper-q4-ram-hint",
            date = "2026-06-01",
            companionVersion = "v0.15.6",
            watchVersion = null,
            title = "Faster Whisper models + RAM hint",
            description = "New q4_0 quantised Tiny / Base / Small variants. Each model row now shows the approximate RAM cost.",
            sampleQuery = null,
            docsPath = "features/#models-optional",
        ),
        FeatureEntry(
            id = "backup-per-category-selection",
            date = "2026-05-31",
            companionVersion = "v0.15.0",
            watchVersion = null,
            title = "Per-category backup selection",
            description = "Pick exactly what your backup includes. Sensitive items (API keys, headers) default to OFF.",
            sampleQuery = null,
            docsPath = "features/#companion-side-features",
        ),
        FeatureEntry(
            id = "ask-agent",
            date = "2026-05-31",
            companionVersion = "v0.14.0",
            watchVersion = "v0.8.0",
            title = "Ask Agent (LLM + MCP tools)",
            description = "Route voice queries to any LLM you configure. Optional MCP tool calling lets the LLM take live actions.",
            sampleQuery = "ask agent what's the capital of France",
            docsPath = "voice-commands/#ask-agent-llm-passthrough",
        ),
        FeatureEntry(
            id = "weather",
            date = "2026-05-31",
            companionVersion = "v0.13.0",
            watchVersion = "v0.7.1",
            title = "Weather",
            description = "Voice weather for any city or your current location. open-meteo by default, OpenWeather optional.",
            sampleQuery = "weather in Tokyo",
            docsPath = "voice-commands/#weather",
        ),
        FeatureEntry(
            id = "world-clock-calculator",
            date = "2026-05-29",
            companionVersion = "v0.12.0",
            watchVersion = "v0.7.0",
            title = "World clock & calculator",
            description = "Time in any city, plus on-device arithmetic with spoken operators. Both fully offline.",
            sampleQuery = "what time is it in Tokyo",
            docsPath = "voice-commands/#world-clock",
        ),
        FeatureEntry(
            id = "alarms-timers",
            date = "2026-05-28",
            companionVersion = "v0.11.0",
            watchVersion = "v0.6.1",
            title = "Alarms & timers",
            description = "Set alarms and countdown timers by voice. The system Clock app handles the ring.",
            sampleQuery = "set a timer for 5 minutes",
            docsPath = "voice-commands/#alarms-timers",
        ),
        FeatureEntry(
            id = "view-learned-phrases",
            date = "2026-05-25",
            companionVersion = "v0.10.1",
            watchVersion = null,
            title = "See and prune learned phrases",
            description = "View — and individually delete — phrases Wristotle has learned from your voice commands.",
            sampleQuery = null,
            docsPath = "features/#settings-tab-whats-in-each-category",
        ),
        FeatureEntry(
            id = "contact-aliases",
            date = "2026-05-25",
            companionVersion = "v0.10.0",
            watchVersion = null,
            title = "Contact aliases",
            description = "Map a spoken phrase to the right contact — fixes the \"Whisper mishears my friend's name\" problem.",
            sampleQuery = null,
            docsPath = "features/#settings-tab-whats-in-each-category",
        ),
        FeatureEntry(
            id = "tasks",
            date = "2026-05-24",
            companionVersion = "v0.9.0",
            watchVersion = "v0.6.0",
            title = "Tasks",
            description = "Voice-controlled checklist with on-watch picker and a companion Tasks tab. Included in backups.",
            sampleQuery = "add task call mom",
            docsPath = "voice-commands/#tasks",
        ),
        FeatureEntry(
            id = "messaging-apps",
            date = "2026-05-24",
            companionVersion = "v0.8.5",
            watchVersion = null,
            title = "WhatsApp / Telegram / Signal messaging",
            description = "Voice messaging across SMS plus three third-party apps via one intent. (Third-party apps need a tap to send.)",
            sampleQuery = "WhatsApp mom on my way",
            docsPath = "voice-commands/#sms-and-other-messaging-apps",
        ),
        FeatureEntry(
            id = "open-app-reliable",
            date = "2026-05-24",
            companionVersion = "v0.8.3",
            watchVersion = null,
            title = "Reliable \"open <app>\" from the watch",
            description = "Cold-start launch of any installed app from the watch (needs Display over other apps).",
            sampleQuery = "open Spotify",
            docsPath = "voice-commands/#open-any-app",
        ),
        FeatureEntry(
            id = "settings-drill-down",
            date = "2026-05-23",
            companionVersion = "v0.8.0",
            watchVersion = null,
            title = "Settings drill-down navigation",
            description = "Settings reorganised into focused sub-screens you reach with one tap from a landing list.",
            sampleQuery = null,
            docsPath = "features/#settings-tab-whats-in-each-category",
        ),
        FeatureEntry(
            id = "confirm-before-dispatch",
            date = "2026-05-23",
            companionVersion = "v0.7.0",
            watchVersion = "v0.5.0",
            title = "Confirm before dispatch",
            description = "Optional watch prompt before destructive actions (call, text, alarm). Configurable timeout + default.",
            sampleQuery = null,
            docsPath = "features/#settings-tab-whats-in-each-category",
        ),
        FeatureEntry(
            id = "backup-restore",
            date = "2026-05-23",
            companionVersion = "v0.6.0",
            watchVersion = null,
            title = "Backup & Restore",
            description = "Export your data to a single ZIP and import it on a fresh install. AES-256 encryption optional.",
            sampleQuery = null,
            docsPath = "features/#companion-side-features",
        ),
        FeatureEntry(
            id = "notes-quicklaunch-aliases",
            date = "2026-05-22",
            companionVersion = "v0.5.0",
            watchVersion = "v0.4.0",
            title = "Voice notes, Quick Launch, App aliases",
            description = "Take voice notes, jump to dictation with a single watch press, and alias app names you call things differently.",
            sampleQuery = "take a note buy milk",
            docsPath = "voice-commands/#notes",
        ),
        FeatureEntry(
            id = "reminder-list-reschedule",
            date = "2026-05-21",
            companionVersion = "v0.4.0",
            watchVersion = "v0.3.1",
            title = "Reminder list & reschedule",
            description = "Ask what's pending; push a reminder to a new time. The watch hint routes cleanly into list / set / reschedule.",
            sampleQuery = "is there a reminder at 2pm",
            docsPath = "voice-commands/#list-reminders",
        ),
        FeatureEntry(
            id = "voice-calendar",
            date = "2026-05-19",
            companionVersion = "v0.3.0",
            watchVersion = null,
            title = "Voice calendar",
            description = "Schedule events and ask what's coming up. Reads your default calendar.",
            sampleQuery = "schedule a meeting with Alex at 3pm",
            docsPath = "voice-commands/#calendar",
        ),
        FeatureEntry(
            id = "watch-settings-from-phone",
            date = "2026-05-19",
            companionVersion = "v0.2.0",
            watchVersion = null,
            title = "Watch settings from the phone",
            description = "Configure watch-side toggles (font sizes, hints, defaults) from the companion app.",
            sampleQuery = null,
            docsPath = "features/#settings-sync",
        ),
        FeatureEntry(
            id = "initial-release",
            date = "2026-05-18",
            companionVersion = "v0.1.0",
            watchVersion = null,
            title = "Initial release",
            description = "Calls, SMS, time-based reminders, media play / pause / next / previous / seek, find phone. All on-device.",
            sampleQuery = "call mom",
            docsPath = "voice-commands/",
        ),
    )
}
