package com.lazydevs.wristotle.help

/**
 * Static help content surfaced under Settings → ❓ Help.
 *
 * ## Layering
 *
 * Two sources, each owning a different concern:
 *
 *  - **`tips`** — hand-edited below. Action-oriented pointers a user
 *    might not discover by tapping around. Not tied to releases; lives
 *    here in code with the rest of the Settings UI.
 *  - **`timeline`** — generated by `tools/regenerate_help_timeline.py`
 *    from `data/features.json`, which is itself a synced snapshot of
 *    `wristotle-docs/data/features.json` (the canonical source of
 *    truth for what releases ship what features). Generated file is
 *    `HelpTimeline.kt` (do not edit by hand).
 *
 * Editing flow when shipping a feature:
 *  1. Edit `wristotle-docs/data/features.json` (add a new entry at
 *     the top of `features[]`).
 *  2. Edit `wristotle-docs/docs/changelog.md` (the human-narrative
 *     long-form prose — features.json carries the structured fields,
 *     the changelog carries the story).
 *  3. From companion repo: `tools/sync_features.sh && python3 tools/regenerate_help_timeline.py`.
 *  4. Commit `data/features.json` + the regenerated `HelpTimeline.kt`
 *     in the companion repo; commit features.json + changelog.md in
 *     the docs repo.
 *
 * Internals-only releases (test / refactor / CI / build / fix) skip
 * features.json entirely — the editorial filter survives by virtue of
 * "no entry, no row." Pre-push hook surfaces a soft warning so the
 * skip decision is conscious.
 *
 * ## Style guide for new entries in features.json
 *
 *  - **`id`** — kebab-case slug, stable across renames. Used as a key
 *    in the JSON; never displayed.
 *  - **`title`** — 3-7 words, capitalised feature name. Subtitle goes
 *    after an em-dash (`—`) or in parens.
 *  - **`description`** — ONE sentence, ~10-20 words. Subject implicit
 *    (the feature itself). Critical caveats in parens at the tail.
 *    Don't recap the title — describe what it DOES. The docs link
 *    carries the depth.
 *  - **`sample_query`** — exactly what a user would say, lowercase, no
 *    surrounding quotes (the renderer adds `Try: "…"`). Omit for
 *    features without a natural voice command (Settings UX, backup,
 *    aliases — anything you reach by tap).
 *  - **`docs_path`** — most specific anchor that exists on the docs
 *    site. Voice-driven features → `voice-commands/#<anchor>`; UX +
 *    Settings → `features/#<anchor>`; problem-solving tips →
 *    `troubleshooting/#<anchor>`. Verify the anchor by grepping
 *    `wristotle-docs/docs/<page>.md`.
 *  - **`companion_version` / `watch_version`** — match the git tags
 *    exactly (`v0.X.Y`). At least one is required; either can be
 *    `null` if the release only touched the other side.
 *  - **`date`** — ISO date matching the tag's commit date.
 *
 * When in doubt, copy a neighbour and adapt. The point of the style
 * guide is consistency, not novelty.
 */
data class FeatureEntry(
    /** Stable kebab-case identifier from features.json. */
    val id: String,
    /** ISO date, e.g. `"2026-06-01"`. */
    val date: String,
    /** Companion git tag (`v0.X.Y`) or null if the release only touched the watch. */
    val companionVersion: String?,
    /** Watch git tag (`v0.X.Y`) or null if the release only touched the companion. */
    val watchVersion: String?,
    /** One-line headline, plain English. */
    val title: String,
    /** Single-sentence description. Keep it short — the docs link
     *  carries the depth. */
    val description: String,
    /** Optional voice-command example. Renders as "Try: …". */
    val sampleQuery: String? = null,
    /** Relative path on the docs site, including any `#anchor`.
     *  Resolved against [HelpContent.DOCS_BASE_URL]. */
    val docsPath: String? = null,
)

/**
 * A short, action-oriented tip — the kind of thing a user might not
 * discover by tapping around. Surfaced at the top of the Help page.
 *
 * Tips are NOT release-tied; they're discovery hints that stay
 * relevant across versions. Hand-edited in this file.
 */
data class Tip(
    val title: String,
    val body: String,
    /** Optional docs deep-link. Resolved against [HelpContent.DOCS_BASE_URL]. */
    val docsPath: String? = null,
)

object HelpContent {

    /** Docs site base. Every entry's relative path resolves against this. */
    const val DOCS_BASE_URL = "https://wristotle.codeberg.page/"

    /** Troubleshooting page — surfaced as a CTA at the bottom of the
     *  Help card. */
    const val TROUBLESHOOTING_PATH = "troubleshooting/"

    /** Top-of-page tips — the things a user is most likely to miss.
     *  Hand-edited (NOT generated). */
    val tips: List<Tip> = listOf(
        Tip(
            title = "Add your own wake words",
            body = "Settings → ✨ Ask Agent → Custom trigger words lets you pick the name you'd call your assistant (e.g. \"Jarvis\"). Then bare or with \"ask\" — both work.",
            docsPath = "voice-commands/#ask-agent-llm-passthrough",
        ),
        Tip(
            title = "Confirm before sending",
            body = "Worried about voice misfires? Turn on Settings → ⌚ Watch → Confirm before sending and the watch prompts before calls / texts / alarms fire.",
            docsPath = "troubleshooting/#confirm-before-send-toggle-is-on-but-my-command-didnt-prompt",
        ),
        Tip(
            title = "Whisper hears the wrong name?",
            body = "Map the spoken phrase to the right contact under Settings → ⌚ Watch → Contact aliases. No need to rename the contact itself.",
            docsPath = "troubleshooting/#wristotle-keeps-mishearing-the-same-contact-or-app-name",
        ),
        Tip(
            title = "Encrypt your backups",
            body = "Set a password under Settings → 💾 Backup and the ZIP encrypts with AES-256. Without one, anyone with the file can read its contents.",
            docsPath = "features/#companion-side-features",
        ),
    )

    /**
     * Feature timeline, newest first. Delegated to the generated
     * [HelpTimeline] object — see KDoc at the top of this file for
     * the editing flow.
     */
    val timeline: List<FeatureEntry> get() = HelpTimeline.timeline
}
