package com.lazydevs.wristotle.help

/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Regenerate via:
 *   tools/sync_features.sh                  # pull data/features.json from docs
 *   python3 tools/regenerate_help_timeline.py
 *
 * Canonical source: wristotle-docs/data/features.json.
 * Style guide for new entries: HelpContent.kt's file-level KDoc.
 */
internal object HelpTimeline {
    val timeline: List<FeatureEntry> = listOf(
        FeatureEntry(
            id = "alarms-v2",
            date = "2026-06-02",
            companionVersion = "v0.18.0",
            watchVersion = "v0.10.0",
            title = "Alarms with phone / watch / both destinations",
            description = "Re-do of the alarm feature. Settings → ⏰ Alarms & Reminders → Alarms — create one-shot alarms via the editor (time + label + destination: Phone / Watch / Both) or by voice (\"set an alarm for 7am\" honours the default-destination dropdown). \"Cancel the alarm\" / \"cancel 7am alarm\" cancels watch alarms; phone alarms still have to be dismissed in the system clock. New BUTTON_ACTION_ALARMS = 4 lets you bind SELECT / long-press UP / long-press DOWN to the on-watch alarm list.",
            sampleQuery = "set an alarm for 7am",
            docsPath = "features/#on-watch-ui",
        ),
        FeatureEntry(
            id = "configurable-chat-buttons",
            date = "2026-06-01",
            companionVersion = "v0.17.0",
            watchVersion = "v0.9.0",
            title = "Configurable chat-surface shortcuts",
            description = "Bind SELECT, long-press UP, and long-press DOWN on the watch chat screen to any of Dictation, Quick menu (chooser), Notes, or Tasks. Defaults keep the existing muscle memory. Edit via Wristotle's gear-icon settings or the companion's Watch settings card.",
            sampleQuery = null,
            docsPath = "features/#on-watch-ui",
        ),
        FeatureEntry(
            id = "help-page",
            date = "2026-06-01",
            companionVersion = "v0.16.2",
            watchVersion = null,
            title = "In-app Help page",
            description = "Settings → ❓ Help. Searchable feature history (newest first), discovery tips, deep-links into the docs. Shows watch versions alongside companion versions for paired releases.",
            sampleQuery = null,
            docsPath = "features/#settings-tab-whats-in-each-category",
        ),
        FeatureEntry(
            id = "custom-ask-agent-triggers",
            date = "2026-06-01",
            companionVersion = "v0.16.0",
            watchVersion = null,
            title = "Custom Ask Agent trigger words",
            description = "Add your own wake words for Ask Agent — works as a verb (\"ask jarvis …\") or bare (\"Jarvis, …\").",
            sampleQuery = "Jarvis, what's the weather?",
            docsPath = "voice-commands/#ask-agent-llm-passthrough",
        ),
        FeatureEntry(
            id = "whisper-q4-ram-hint",
            date = "2026-06-01",
            companionVersion = "v0.15.6",
            watchVersion = null,
            title = "Faster Whisper models + RAM hint",
            description = "New q4_0 quantised Tiny / Base / Small variants. Each model row now shows the approximate RAM cost.",
            sampleQuery = null,
            docsPath = "features/#models-optional",
        ),
        FeatureEntry(
            id = "backup-per-category-selection",
            date = "2026-05-31",
            companionVersion = "v0.15.0",
            watchVersion = null,
            title = "Per-category backup selection",
            description = "Pick exactly what your backup includes. Sensitive items (API keys, headers) default to OFF.",
            sampleQuery = null,
            docsPath = "features/#companion-side-features",
        ),
        FeatureEntry(
            id = "ask-agent",
            date = "2026-05-31",
            companionVersion = "v0.14.0",
            watchVersion = "v0.8.0",
            title = "Ask Agent (LLM + MCP tools)",
            description = "Route voice queries to any LLM you configure. Optional MCP tool calling lets the LLM take live actions.",
            sampleQuery = "ask agent what's the capital of France",
            docsPath = "voice-commands/#ask-agent-llm-passthrough",
        ),
        FeatureEntry(
            id = "weather",
            date = "2026-05-31",
            companionVersion = "v0.13.0",
            watchVersion = "v0.7.1",
            title = "Weather",
            description = "Voice weather for any city or your current location. open-meteo by default, OpenWeather optional.",
            sampleQuery = "weather in Tokyo",
            docsPath = "voice-commands/#weather",
        ),
        FeatureEntry(
            id = "world-clock-calculator",
            date = "2026-05-29",
            companionVersion = "v0.12.0",
            watchVersion = "v0.7.0",
            title = "World clock & calculator",
            description = "Time in any city, plus on-device arithmetic with spoken operators. Both fully offline.",
            sampleQuery = "what time is it in Tokyo",
            docsPath = "voice-commands/#world-clock",
        ),
        FeatureEntry(
            id = "alarms-timers",
            date = "2026-05-28",
            companionVersion = "v0.11.0",
            watchVersion = "v0.6.1",
            title = "Alarms & timers",
            description = "Set alarms and countdown timers by voice. The system Clock app handles the ring.",
            sampleQuery = "set a timer for 5 minutes",
            docsPath = "voice-commands/#alarms-timers",
        ),
        FeatureEntry(
            id = "view-learned-phrases",
            date = "2026-05-25",
            companionVersion = "v0.10.1",
            watchVersion = null,
            title = "See and prune learned phrases",
            description = "View — and individually delete — phrases Wristotle has learned from your voice commands.",
            sampleQuery = null,
            docsPath = "features/#settings-tab-whats-in-each-category",
        ),
        FeatureEntry(
            id = "contact-aliases",
            date = "2026-05-25",
            companionVersion = "v0.10.0",
            watchVersion = null,
            title = "Contact aliases",
            description = "Map a spoken phrase to the right contact — fixes the \"Whisper mishears my friend's name\" problem.",
            sampleQuery = null,
            docsPath = "features/#settings-tab-whats-in-each-category",
        ),
        FeatureEntry(
            id = "tasks",
            date = "2026-05-24",
            companionVersion = "v0.9.0",
            watchVersion = "v0.6.0",
            title = "Tasks",
            description = "Voice-controlled checklist with on-watch picker and a companion Tasks tab. Included in backups.",
            sampleQuery = "add task call mom",
            docsPath = "voice-commands/#tasks",
        ),
        FeatureEntry(
            id = "messaging-apps",
            date = "2026-05-24",
            companionVersion = "v0.8.5",
            watchVersion = null,
            title = "WhatsApp / Telegram / Signal messaging",
            description = "Voice messaging across SMS plus three third-party apps via one intent. (Third-party apps need a tap to send.)",
            sampleQuery = "WhatsApp mom on my way",
            docsPath = "voice-commands/#sms-and-other-messaging-apps",
        ),
        FeatureEntry(
            id = "open-app-reliable",
            date = "2026-05-24",
            companionVersion = "v0.8.3",
            watchVersion = null,
            title = "Reliable \"open <app>\" from the watch",
            description = "Cold-start launch of any installed app from the watch (needs Display over other apps).",
            sampleQuery = "open Spotify",
            docsPath = "voice-commands/#open-any-app",
        ),
        FeatureEntry(
            id = "settings-drill-down",
            date = "2026-05-23",
            companionVersion = "v0.8.0",
            watchVersion = null,
            title = "Settings drill-down navigation",
            description = "Settings reorganised into focused sub-screens you reach with one tap from a landing list.",
            sampleQuery = null,
            docsPath = "features/#settings-tab-whats-in-each-category",
        ),
        FeatureEntry(
            id = "confirm-before-dispatch",
            date = "2026-05-23",
            companionVersion = "v0.7.0",
            watchVersion = "v0.5.0",
            title = "Confirm before dispatch",
            description = "Optional watch prompt before destructive actions (call, text, alarm). Configurable timeout + default.",
            sampleQuery = null,
            docsPath = "features/#settings-tab-whats-in-each-category",
        ),
        FeatureEntry(
            id = "backup-restore",
            date = "2026-05-23",
            companionVersion = "v0.6.0",
            watchVersion = null,
            title = "Backup & Restore",
            description = "Export your data to a single ZIP and import it on a fresh install. AES-256 encryption optional.",
            sampleQuery = null,
            docsPath = "features/#companion-side-features",
        ),
        FeatureEntry(
            id = "notes-quicklaunch-aliases",
            date = "2026-05-22",
            companionVersion = "v0.5.0",
            watchVersion = "v0.4.0",
            title = "Voice notes, Quick Launch, App aliases",
            description = "Take voice notes, jump to dictation with a single watch press, and alias app names you call things differently.",
            sampleQuery = "take a note buy milk",
            docsPath = "voice-commands/#notes",
        ),
        FeatureEntry(
            id = "reminder-list-reschedule",
            date = "2026-05-21",
            companionVersion = "v0.4.0",
            watchVersion = "v0.3.1",
            title = "Reminder list & reschedule",
            description = "Ask what's pending; push a reminder to a new time. The watch hint routes cleanly into list / set / reschedule.",
            sampleQuery = "is there a reminder at 2pm",
            docsPath = "voice-commands/#list-reminders",
        ),
        FeatureEntry(
            id = "voice-calendar",
            date = "2026-05-19",
            companionVersion = "v0.3.0",
            watchVersion = null,
            title = "Voice calendar",
            description = "Schedule events and ask what's coming up. Reads your default calendar.",
            sampleQuery = "schedule a meeting with Alex at 3pm",
            docsPath = "voice-commands/#calendar",
        ),
        FeatureEntry(
            id = "watch-settings-from-phone",
            date = "2026-05-19",
            companionVersion = "v0.2.0",
            watchVersion = null,
            title = "Watch settings from the phone",
            description = "Configure watch-side toggles (font sizes, hints, defaults) from the companion app.",
            sampleQuery = null,
            docsPath = "features/#settings-sync",
        ),
        FeatureEntry(
            id = "initial-release",
            date = "2026-05-18",
            companionVersion = "v0.1.0",
            watchVersion = null,
            title = "Initial release",
            description = "Calls, SMS, time-based reminders, media play / pause / next / previous / seek, find phone. All on-device.",
            sampleQuery = "call mom",
            docsPath = "voice-commands/",
        ),
    )
}
