// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2025-2026 Lazy Devs

package com.lazydevs.wristotle.speech.nlu.transport

/**
 * AppMessage key indices shared between the Pebble watch app and this
 * companion (and any future iOS companion).
 *
 * These values are auto-generated by the Pebble SDK from the `messageKeys`
 * array in the watch app's `package.json`. The source of truth is
 * `build/src/message_keys.auto.c` in the Wristotle watch app.
 *
 * R4 batch 3 — lifted from :app/transport. Pure UInt/Int/Char constants;
 * no platform deps.
 */
object MessageKeys {
    /** Watch → phone: ring the phone for "find my phone". Tagged with [MSG_TARGET]
     *  = companion when routed here; the companion plays it on the alarm stream. */
    val FIND_PHONE: UInt         = 10001u
    val REMINDER_QUERY: UInt     = 10004u
    val REMINDER_RESULT: UInt    = 10005u
    val CANCEL_QUERY: UInt       = 10006u
    val CANCEL_RESULT: UInt      = 10007u
    val COMPANION_PING: UInt     = 10009u
    val COMPANION_READY: UInt    = 10010u
    val COMPANION_QUERY: UInt    = 10011u
    val COMPANION_RESPONSE: UInt = 10012u
    val MSG_TARGET: UInt         = 10014u

    /** Watch → companion logging payload (locally-handled commands the companion
     *  never sees through query channels). All three keys arrive in one message. */
    val LOG_QUERY: UInt          = 10023u
    val LOG_RESPONSE: UInt       = 10024u
    val LOG_HANDLER: UInt        = 10025u

    /** Settings sync — the 10 watch-persisted settings the companion mirrors. */
    val SETTING_LOGGING: UInt                  = 10000u
    val SETTING_DICTATION_CONFIRMATION: UInt   = 10008u
    val SETTING_FIND_PHONE_TARGET: UInt        = 10015u
    val SETTING_REMINDERS_TARGET: UInt         = 10016u
    val SETTING_CANCEL_TARGET: UInt            = 10017u
    val SETTING_QUICK_LAUNCH_AUTO_EXIT: UInt   = 10018u
    // 10065 — next free key after SHOW_CODE_INDEX (10064); appended last in the
    // watch package.json messageKeys so its positional id stays 10065.
    val SETTING_CODE_DISPLAY_SECONDS: UInt     = 10065u
    val SETTING_VIBRATE_ON_LAUNCH: UInt        = 10019u
    val SETTING_VIBRATE_ON_QUICK_LAUNCH: UInt  = 10020u
    val SETTING_VIBRATE_RESPECT_QUIET: UInt    = 10021u
    val SETTING_SKIP_RETRY_DIALOG: UInt        = 10022u
    val SETTING_QUICK_LAUNCH_ACTION: UInt      = 10031u

    /** Quick Launch action wire values. Stable; persisted on the watch. */
    const val QUICK_LAUNCH_ACTION_DICTATE: Int = 0
    const val QUICK_LAUNCH_ACTION_NOTES: Int   = 1
    const val QUICK_LAUNCH_ACTION_MENU: Int    = 2

    /** Chat-surface button shortcuts. */
    val SETTING_LONG_PRESS_UP_ACTION: UInt   = 10042u
    val SETTING_LONG_PRESS_DOWN_ACTION: UInt = 10043u
    val SETTING_SELECT_ACTION: UInt          = 10044u

    /** Master "Enable color theme" toggle. */
    val SETTING_COLOR_THEME: UInt            = 10053u

    /** Chat-surface button-action wire values. Stable; persisted on the watch. */
    const val BUTTON_ACTION_MENU: Int      = 0
    const val BUTTON_ACTION_NOTES: Int     = 1
    const val BUTTON_ACTION_TASKS: Int     = 2
    const val BUTTON_ACTION_DICTATION: Int = 3
    const val BUTTON_ACTION_ALARMS: Int    = 4
    const val BUTTON_ACTION_CODES: Int     = 5

    /** Alarms wire — companion → watch SET / CANCEL / LIST + watch → companion
     *  result + presence-only SHOW_LIST trigger. */
    val ALARM_SET_EPOCH: UInt      = 10045u
    val ALARM_SET_LABEL: UInt      = 10046u
    val ALARM_SET_RESULT: UInt     = 10047u
    val ALARM_CANCEL_EPOCH: UInt   = 10048u
    val ALARM_CANCEL_RESULT: UInt  = 10049u
    val ALARMS_REQUEST: UInt       = 10050u
    val ALARMS_RESPONSE: UInt      = 10051u
    val ALARMS_SHOW_LIST: UInt     = 10052u

    /** Companion → watch: presence-only ping that asks the watch to ship back a
     *  snapshot containing every SETTING_* key + its current value. */
    val REQUEST_SETTINGS: UInt   = 10026u

    /** Notes-on-watch (Phase C). */
    val NOTES_REQUEST: UInt      = 10027u
    val NOTES_RESPONSE: UInt     = 10028u

    /** Per-note detail fetch. */
    val NOTE_DETAIL_REQUEST: UInt  = 10029u
    val NOTE_DETAIL_RESPONSE: UInt = 10030u

    /** Confirm-before-dispatch toggle (dual-use SETTING and per-query flag). */
    val SETTING_CONFIRM_BEFORE_SEND: UInt = 10032u
    val CONFIRM_PROMPT: UInt   = 10033u
    val CONFIRM_RESPONSE: UInt = 10034u
    val SETTING_CONFIRM_TIMEOUT_SECONDS: UInt = 10035u
    val SETTING_CONFIRM_DEFAULT_SEND: UInt = 10036u

    /** Tasks-on-watch (Phase B). */
    val TASKS_REQUEST: UInt  = 10037u
    val TASKS_RESPONSE: UInt = 10038u

    /** Filter values for [TASKS_REQUEST]. */
    const val TASKS_FILTER_PENDING: Int   = 0
    const val TASKS_FILTER_COMPLETED: Int = 1
    const val TASKS_FILTER_ALL: Int       = 2

    /** Per-task quick-complete. */
    val TASK_COMPLETE_REQUEST: UInt  = 10039u
    val TASK_COMPLETE_RESPONSE: UInt = 10040u

    /** Mid-query status from AskAgent's MCP tool-calling loop. */
    val AGENT_STATUS: UInt = 10041u

    // ── TTS spike (2026-06-09) — emery-only, validate BLE bandwidth ─────
    /** Open the speaker stream. UInt8(1) payload, no other data. Sent in the
     *  same AppMessage as the first chunk so the round-trip cost is paid once. */
    val TTS_START: UInt = 10054u
    /** Raw 8 kHz / 8-bit signed mono PCM. Up to ~6 KB per chunk on emery
     *  (inbox is sized to `app_message_inbox_size_maximum()`). */
    val TTS_PCM_CHUNK: UInt = 10055u
    /** Flush + close the speaker stream. UInt8(1) payload. Watch logs
     *  throughput stats on receipt — that's the spike's measurement signal. */
    val TTS_END: UInt = 10056u

    /** Companion → watch: a "card kind" hint sent in the SAME frame as the
     *  response so the watch can render a richer full-screen card instead of a
     *  plain chat bubble (e.g. "sport"). Empty/absent ⇒ plain bubble. */
    val CARD_KIND: UInt = 10057u

    /** Companion → watch: optional structured card payload (US-0x1F-delimited)
     *  the watch renders visually — e.g. a sports scoreboard. Same frame as the
     *  response + [CARD_KIND]. */
    val CARD_DATA: UInt = 10058u

    /** Companion → watch: result status paired with a response in the SAME
     *  frame. Sent as text "1" ONLY when the action failed (contact not found,
     *  unknown command, permission denied, …); absent ⇒ success. The watch
     *  idles a failed result on-screen (cancels the quick-launch auto-exit) so
     *  a silent failure stays visible until the user presses BACK. Old firmware
     *  ignores the unknown key and keeps the pre-1.6 auto-exit behaviour. */
    val RESULT_STATUS: UInt = 10066u

    /** [RESULT_STATUS] value that means "the action failed". */
    const val RESULT_STATUS_FAILED: String = "1"

    /** Companion → watch: paired with an Ask Agent answer when conversation
     *  context is live (issue #25), so the chat UI can show a "context on"
     *  indicator. Sent as text "1" only when active; absent ⇒ no context. */
    val CONTEXT_ACTIVE: UInt = 10067u

    /** [CONTEXT_ACTIVE] value meaning "conversation context is live". */
    const val CONTEXT_ACTIVE_ON: String = "1"

    /** Watch → companion: the watch app's version string, piggybacked on the
     *  launch COMPANION_PING. Cached by the companion (a watchapp only runs when
     *  launched) and surfaced in the diagnostics bundle. */
    val WATCH_APP_VERSION: UInt = 10059u

    /** Saved-codes sync (companion → watch). One frame per code carries all four:
     *  [CODE_SYNC_INDEX] (0-based; index 0 means "clear the cache first"),
     *  [CODE_SYNC_COUNT] (total; 0 = no codes, just clear), [CODE_SYNC_LABEL]
     *  (display name), [CODE_SYNC_MATRIX] (CodeWire bytes the watch draws). */
    val CODE_SYNC_INDEX: UInt  = 10060u
    val CODE_SYNC_COUNT: UInt  = 10061u
    val CODE_SYNC_LABEL: UInt  = 10062u
    val CODE_SYNC_MATRIX: UInt = 10063u

    /** Voice recall — companion tells the watch to render the cached code at
     *  this 0-based index (matches the [CODE_SYNC_INDEX] order). */
    val SHOW_CODE_INDEX: UInt = 10064u

    /** Cap on a single per-note detail body sent over [NOTE_DETAIL_RESPONSE]. */
    const val NOTE_DETAIL_MAX_CHARS: Int = 540

    /** Record-separator char (US-ASCII 0x1E) used to delimit notes inside a
     *  single NOTES_RESPONSE payload. Never appears in printable text so
     *  splitting is unambiguous. */
    const val NOTES_SEPARATOR: Char = ''

    /** Record-separator (US-ASCII 0x1E) — between tasks in TASKS_RESPONSE. */
    const val TASKS_RECORD_SEPARATOR: Char = ''

    /** Unit-separator (US-ASCII 0x1F) — between the id and text of a single
     *  task in TASKS_RESPONSE. */
    const val TASKS_UNIT_SEPARATOR: Char = ''

    /** Cap on the [TASKS_RESPONSE] CSTRING payload. */
    const val TASKS_RESPONSE_MAX_CHARS: Int = 600

    /** All settings keys, grouped so the listener service can detect "this
     *  incoming message carries settings tuples" without a marker key. */
    val SETTING_KEYS: List<UInt> = listOf(
        SETTING_LOGGING,
        SETTING_DICTATION_CONFIRMATION,
        SETTING_FIND_PHONE_TARGET,
        SETTING_REMINDERS_TARGET,
        SETTING_CANCEL_TARGET,
        SETTING_QUICK_LAUNCH_AUTO_EXIT,
        SETTING_CODE_DISPLAY_SECONDS,
        SETTING_VIBRATE_ON_LAUNCH,
        SETTING_VIBRATE_ON_QUICK_LAUNCH,
        SETTING_VIBRATE_RESPECT_QUIET,
        SETTING_SKIP_RETRY_DIALOG,
        SETTING_QUICK_LAUNCH_ACTION,
        SETTING_CONFIRM_TIMEOUT_SECONDS,
        SETTING_CONFIRM_DEFAULT_SEND,
        SETTING_LONG_PRESS_UP_ACTION,
        SETTING_LONG_PRESS_DOWN_ACTION,
        SETTING_SELECT_ACTION,
        SETTING_COLOR_THEME,
    )

    /** Value of MSG_TARGET that means "this message is for the Android companion". */
    const val TARGET_COMPANION: Int = 1
}
