// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2025-2026 Lazy Devs

package com.lazydevs.wristotle.backup

import com.lazydevs.wristotle.mcp.McpServerEntity
import org.json.JSONObject

/**
 * Per-entity JSON codec for [McpServerEntity]. Same contract as
 * [NoteJson] / [TaskJson]: encoder emits the current [CURRENT_SCHEMA]
 * shape; decoder branches on the wrapper's `schema:` field.
 *
 * The `auth_header` field is intentionally **encoded only when supplied
 * by the caller** — the BackupExporter strips it from each row when
 * the user didn't tick the "MCP auth headers" secret checkbox. The
 * decoder defaults missing `auth_header` to null, restoring servers
 * without auth (user re-pastes per server post-restore).
 */
object McpServerJson {

    const val CURRENT_SCHEMA = 1

    /**
     * @param includeAuthHeader When false, `auth_header` is omitted from
     *   the encoded row even if [server.authHeader] is non-null. The
     *   exporter passes false when the user didn't tick the secret
     *   checkbox; the row still rides along, just without the secret.
     */
    fun encode(server: McpServerEntity, includeAuthHeader: Boolean): JSONObject = JSONObject().apply {
        put("id", server.id)
        put("name", server.name)
        put("url", server.url)
        put("streamable", server.streamable)
        if (includeAuthHeader && server.authHeader != null) {
            put("auth_header", server.authHeader)
        }
        put("enabled", server.enabled)
    }

    fun decode(row: JSONObject, schema: Int): McpServerEntity = when (schema) {
        1 -> McpServerEntity(
            // id is auto-generated by Room; ignore the source id on restore
            // so a fresh insert assigns a new local id. Avoids cross-device
            // id-collision when merging with existing rows.
            id = 0L,
            name = row.optString("name", ""),
            url = row.optString("url", ""),
            streamable = row.optBoolean("streamable", true),
            authHeader = row.optString("auth_header").takeIf { it.isNotEmpty() },
            enabled = row.optBoolean("enabled", true),
        )
        else -> throw IllegalArgumentException(
            "Unsupported McpServerJson schema $schema (max $CURRENT_SCHEMA)"
        )
    }
}