package com.lazydevs.wristotle.transport

/**
 * AppMessage key indices shared between the Pebble watch app and this companion.
 *
 * These values are auto-generated by the Pebble SDK from the `messageKeys` array
 * in the watch app's `package.json`. The source of truth is
 * `build/src/message_keys.auto.c` in the Wristotle watch app.
 */
object MessageKeys {
    val REMINDER_QUERY: UInt     = 10004u
    val REMINDER_RESULT: UInt    = 10005u
    val CANCEL_QUERY: UInt       = 10006u
    val CANCEL_RESULT: UInt      = 10007u
    val COMPANION_PING: UInt     = 10009u
    val COMPANION_READY: UInt    = 10010u
    val COMPANION_QUERY: UInt    = 10011u
    val COMPANION_RESPONSE: UInt = 10012u
    val MSG_TARGET: UInt         = 10014u

    /** Watch → companion logging payload (locally-handled commands the companion
     *  never sees through query channels). All three keys arrive in one message. */
    val LOG_QUERY: UInt          = 10023u
    val LOG_RESPONSE: UInt       = 10024u
    val LOG_HANDLER: UInt        = 10025u

    /** Settings sync — the 10 watch-persisted settings the companion mirrors.
     *  Companion → watch: send one of these keys with a new value to update on
     *  the watch (handled by the same C inbox handler PKJS already drives).
     *  Watch → companion: arrives bundled in the response to [REQUEST_SETTINGS]
     *  and parsed by [WatchSettingsRepository]. */
    val SETTING_LOGGING: UInt                  = 10000u
    val SETTING_DICTATION_CONFIRMATION: UInt   = 10008u
    val SETTING_FIND_PHONE_TARGET: UInt        = 10015u
    val SETTING_REMINDERS_TARGET: UInt         = 10016u
    val SETTING_CANCEL_TARGET: UInt            = 10017u
    val SETTING_QUICK_LAUNCH_AUTO_EXIT: UInt   = 10018u
    val SETTING_VIBRATE_ON_LAUNCH: UInt        = 10019u
    val SETTING_VIBRATE_ON_QUICK_LAUNCH: UInt  = 10020u
    val SETTING_VIBRATE_RESPECT_QUIET: UInt    = 10021u
    val SETTING_SKIP_RETRY_DIALOG: UInt        = 10022u
    /** Quick Launch action: which screen Wristotle opens when launched via
     *  the system Quick Launch button. Int32 enum: 0 = dictation (default),
     *  1 = notes. Matches the QuickLaunchAction enum in the watch's config.h. */
    val SETTING_QUICK_LAUNCH_ACTION: UInt      = 10031u

    /** Quick Launch action wire values. Stable; persisted on the watch. */
    const val QUICK_LAUNCH_ACTION_DICTATE: Int = 0
    const val QUICK_LAUNCH_ACTION_NOTES: Int   = 1
    const val QUICK_LAUNCH_ACTION_MENU: Int    = 2

    /** Chat-surface button shortcuts — each Int32 holds one [BUTTON_ACTION_*]
     *  wire value. Long-press UP/DOWN default to the quick chooser
     *  ([BUTTON_ACTION_MENU]); SELECT defaults to dictation
     *  ([BUTTON_ACTION_DICTATION]) so the long-standing "press to talk"
     *  muscle memory keeps working. Matches the LongPressAction enum in
     *  the watch's config.h. */
    val SETTING_LONG_PRESS_UP_ACTION: UInt   = 10042u
    val SETTING_LONG_PRESS_DOWN_ACTION: UInt = 10043u
    val SETTING_SELECT_ACTION: UInt          = 10044u

    /** Master "Enable color theme" toggle. When true the watch lights up
     *  its colored icon variants + a LightGray menu highlight bg + the
     *  ACCENT chat progress strip on color-capable platforms. Default
     *  false on a fresh install; B&W watches are unaffected either way. */
    val SETTING_COLOR_THEME: UInt            = 10053u

    /** Chat-surface button-action wire values. Stable; persisted on the watch.
     *  Every value is legal on every slot — the defaults differ by slot but
     *  the user can bind anything to anything. */
    const val BUTTON_ACTION_MENU: Int      = 0
    const val BUTTON_ACTION_NOTES: Int     = 1
    const val BUTTON_ACTION_TASKS: Int     = 2
    const val BUTTON_ACTION_DICTATION: Int = 3
    const val BUTTON_ACTION_ALARMS: Int    = 4

    /** Alarms wire — companion → watch SET / CANCEL / LIST + watch → companion
     *  result + presence-only SHOW_LIST trigger (used by voice ListAlarms + by
     *  the on-watch Alarms button-action). The watch persists scheduled
     *  alarms across reboots via its `wakeup_service` + `persist_*`. Cancel
     *  with epoch == 0 = cancel ALL pending watch alarms; non-zero epoch =
     *  cancel the slot whose epoch matches. */
    val ALARM_SET_EPOCH: UInt      = 10045u
    val ALARM_SET_LABEL: UInt      = 10046u
    val ALARM_SET_RESULT: UInt     = 10047u
    val ALARM_CANCEL_EPOCH: UInt   = 10048u
    val ALARM_CANCEL_RESULT: UInt  = 10049u
    val ALARMS_REQUEST: UInt       = 10050u
    val ALARMS_RESPONSE: UInt      = 10051u
    val ALARMS_SHOW_LIST: UInt     = 10052u

    /** Companion → watch: presence-only ping that asks the watch to ship back a
     *  snapshot containing every SETTING_* key + its current value. Added in
     *  watch app v0.X.Y; older watch apps ACK but don't respond, which the
     *  repository detects via a response timeout. */
    val REQUEST_SETTINGS: UInt   = 10026u

    /** Notes-on-watch (Phase C). Watch → companion: presence-only request that
     *  asks for the most recent notes. Companion → watch: a single CSTRING
     *  containing notes joined by [NOTES_SEPARATOR] (record separator); each
     *  note is the body, truncated to fit. */
    val NOTES_REQUEST: UInt      = 10027u
    val NOTES_RESPONSE: UInt     = 10028u

    /** Per-note detail fetch. Watch → companion: an Int32 with the note's
     *  index in the most-recent NOTES_RESPONSE (0..N-1). Companion → watch:
     *  the FULL body of that note, capped at [NOTE_DETAIL_MAX_CHARS] to fit
     *  one AppMessage. Used when the user drills into a row on the watch. */
    val NOTE_DETAIL_REQUEST: UInt  = 10029u
    val NOTE_DETAIL_RESPONSE: UInt = 10030u

    /**
     * Confirm-before-dispatch toggle.
     *
     * Dual-use key. As a SETTING (Phase A1), it appears in the snapshot
     * alongside the other watch-persisted settings. As a PER-QUERY FLAG
     * (Phase A2+), the watch includes the same key inside the COMPANION_QUERY
     * dictionary to signal "I want a confirm prompt for this query if its
     * resolved intent is destructive".
     *
     * Deliberately NOT added to [SETTING_KEYS] because the per-query usage
     * would make `PebbleListenerService.isSettingsMessage()` misclassify
     * confirm-enabled queries as settings batches. The snapshot still
     * ingests correctly because it carries 10+ other SETTING_* keys; one
     * missing entry doesn't change the batch detection.
     */
    val SETTING_CONFIRM_BEFORE_SEND: UInt = 10032u

    /**
     * Companion → watch: the rendered confirm prompt text the user sees
     * before SELECT-ing to dispatch (or BACK-ing to cancel). Sent only when
     * the watch's per-query CONFIRM_BEFORE_SEND flag was set AND the
     * routed intent is in the destructive set (see IntentDestructiveness).
     */
    val CONFIRM_PROMPT: UInt   = 10033u

    /**
     * Watch → companion: the user's decision on a pending confirm prompt.
     * Int32 0/1 (0 = cancel, 1 = dispatch). Consumed by PebbleListenerService
     * to either run the stashed IntentResult or log a cancelled entry.
     * Phase A2 stub on the watch always sends 1 (auto-confirm) until the
     * real UI lands in Phase B.
     */
    val CONFIRM_RESPONSE: UInt = 10034u

    /** Auto-resolve timeout for the on-watch confirm prompt, in seconds.
     *  Int32. 0 = "never time out". Whitelisted values: 0 / 5 / 10 / 15 /
     *  30 / 60. Default 15. Lives in the settings snapshot. */
    val SETTING_CONFIRM_TIMEOUT_SECONDS: UInt = 10035u

    /** Bool: when true, the confirm prompt timing out auto-dispatches the
     *  stashed action; when false (default) it cancels. Only meaningful
     *  when [SETTING_CONFIRM_BEFORE_SEND] is on. Lives in the snapshot. */
    val SETTING_CONFIRM_DEFAULT_SEND: UInt = 10036u

    /** Tasks-on-watch (Phase B). Watch → companion: Int32 filter value
     *  selecting which task list to return:
     *      0 = pending (default — also when the Int32 is absent / unknown)
     *      1 = completed
     *      2 = all
     *  See [TASKS_FILTER_PENDING] / [_COMPLETED] / [_ALL].
     *
     *  Companion → watch: a single CSTRING containing tasks framed as
     *  `<id><US><state><US><text><RS>…<id><US><state><US><text>`.
     *  `state` is the literal `"0"` or `"1"` (0 = pending, 1 = completed)
     *  so the watch can render a checkmark prefix in the All / Completed
     *  views. The id is round-tripped so a follow-up
     *  [TASK_COMPLETE_REQUEST] can target the row directly.
     *
     *  Mirrors the NOTES_REQUEST shape but ships id + state alongside
     *  the text (notes-on-watch doesn't need either because
     *  NOTE_DETAIL_REQUEST uses positional index — tasks need the id
     *  because completing one by position would race the underlying
     *  list ordering, and the state because All view shows both
     *  pending and completed inline). */
    val TASKS_REQUEST: UInt  = 10037u
    val TASKS_RESPONSE: UInt = 10038u

    /** Filter values for [TASKS_REQUEST]. Wire-stable; the watch sends
     *  these per-request, and the companion picks the corresponding
     *  TaskRepository method. */
    const val TASKS_FILTER_PENDING: Int   = 0
    const val TASKS_FILTER_COMPLETED: Int = 1
    const val TASKS_FILTER_ALL: Int       = 2

    /** Per-task quick-complete. Watch → companion: Int32 with the task's
     *  id (the value the watch received in [TASKS_RESPONSE]). Companion
     *  → watch: a single CSTRING with the user-facing result
     *  (*"Completed: Buy milk"* / *"No pending tasks"*). */
    val TASK_COMPLETE_REQUEST: UInt  = 10039u
    val TASK_COMPLETE_RESPONSE: UInt = 10040u

    /** Mid-query status from AskAgent's MCP tool-calling loop. CSTRING
     *  payload like *"→ github.get_me"*. Routed to the watch's hint-bar
     *  status slot (NOT the chat surface — the chat renders one bubble
     *  per voice query, so intermediate sendResponse() drops the final
     *  answer; see feedback_watch_chat_single_bubble memory). Cleared
     *  automatically when the final response arrives — the watch's
     *  chat_ui_set_thinking(false) on response restores the normal
     *  "SELECT to speak" hint. */
    val AGENT_STATUS: UInt = 10041u

    /** Cap on a single per-note detail body sent over [NOTE_DETAIL_RESPONSE].
     *  Stays under Pebble's AppMessage outbox budget (~636 bytes) minus
     *  tuple framing. */
    const val NOTE_DETAIL_MAX_CHARS: Int = 540

    /** Record-separator char (US-ASCII 0x1E) used to delimit notes inside a
     *  single NOTES_RESPONSE payload. Never appears in printable text so
     *  splitting is unambiguous. */
    const val NOTES_SEPARATOR: Char = ''

    /** Record-separator (US-ASCII 0x1E) — between tasks in TASKS_RESPONSE. */
    const val TASKS_RECORD_SEPARATOR: Char = ''

    /** Unit-separator (US-ASCII 0x1F) — between the id and text of a single
     *  task in TASKS_RESPONSE. Neither separator appears in printable text
     *  so the split is unambiguous. */
    const val TASKS_UNIT_SEPARATOR: Char = ''

    /** Cap on the [TASKS_RESPONSE] CSTRING payload. Pebble's AppMessage
     *  outbox budget is ~636 bytes; framing overhead + tuple headers
     *  leaves us ~600 bytes of payload to work with. The watch's
     *  TASKS_MAX row cap (16) is the harder limit for typical task
     *  text lengths; this budget only kicks in when many of the tasks
     *  have unusually long bodies. */
    const val TASKS_RESPONSE_MAX_CHARS: Int = 600

    /** All settings keys, grouped so [PebbleListenerService.onMessageReceived]
     *  can detect "this incoming message carries settings tuples" without a
     *  marker key. Any tuple of one of these keys is, by definition, a
     *  settings update from the watch. */
    val SETTING_KEYS: List<UInt> = listOf(
        SETTING_LOGGING,
        SETTING_DICTATION_CONFIRMATION,
        SETTING_FIND_PHONE_TARGET,
        SETTING_REMINDERS_TARGET,
        SETTING_CANCEL_TARGET,
        SETTING_QUICK_LAUNCH_AUTO_EXIT,
        SETTING_VIBRATE_ON_LAUNCH,
        SETTING_VIBRATE_ON_QUICK_LAUNCH,
        SETTING_VIBRATE_RESPECT_QUIET,
        SETTING_SKIP_RETRY_DIALOG,
        SETTING_QUICK_LAUNCH_ACTION,
        SETTING_CONFIRM_TIMEOUT_SECONDS,
        SETTING_CONFIRM_DEFAULT_SEND,
        SETTING_LONG_PRESS_UP_ACTION,
        SETTING_LONG_PRESS_DOWN_ACTION,
        SETTING_SELECT_ACTION,
        SETTING_COLOR_THEME,
    )

    /** Value of MSG_TARGET that means "this message is for the Android companion". */
    const val TARGET_COMPANION: Int = 1
}
