package com.lazydevs.wristotle.transport

/**
 * AppMessage key indices shared between the Pebble watch app and this companion.
 *
 * These values are auto-generated by the Pebble SDK from the `messageKeys` array
 * in the watch app's `package.json`. The source of truth is
 * `build/src/message_keys.auto.c` in the Wristotle watch app.
 */
object MessageKeys {
    val REMINDER_QUERY: UInt     = 10004u
    val REMINDER_RESULT: UInt    = 10005u
    val CANCEL_QUERY: UInt       = 10006u
    val CANCEL_RESULT: UInt      = 10007u
    val COMPANION_PING: UInt     = 10009u
    val COMPANION_READY: UInt    = 10010u
    val COMPANION_QUERY: UInt    = 10011u
    val COMPANION_RESPONSE: UInt = 10012u
    val MSG_TARGET: UInt         = 10014u

    /** Watch → companion logging payload (locally-handled commands the companion
     *  never sees through query channels). All three keys arrive in one message. */
    val LOG_QUERY: UInt          = 10023u
    val LOG_RESPONSE: UInt       = 10024u
    val LOG_HANDLER: UInt        = 10025u

    /** Settings sync — the 10 watch-persisted settings the companion mirrors.
     *  Companion → watch: send one of these keys with a new value to update on
     *  the watch (handled by the same C inbox handler PKJS already drives).
     *  Watch → companion: arrives bundled in the response to [REQUEST_SETTINGS]
     *  and parsed by [WatchSettingsRepository]. */
    val SETTING_LOGGING: UInt                  = 10000u
    val SETTING_DICTATION_CONFIRMATION: UInt   = 10008u
    val SETTING_FIND_PHONE_TARGET: UInt        = 10015u
    val SETTING_REMINDERS_TARGET: UInt         = 10016u
    val SETTING_CANCEL_TARGET: UInt            = 10017u
    val SETTING_QUICK_LAUNCH_AUTO_EXIT: UInt   = 10018u
    val SETTING_VIBRATE_ON_LAUNCH: UInt        = 10019u
    val SETTING_VIBRATE_ON_QUICK_LAUNCH: UInt  = 10020u
    val SETTING_VIBRATE_RESPECT_QUIET: UInt    = 10021u
    val SETTING_SKIP_RETRY_DIALOG: UInt        = 10022u
    /** Quick Launch action: which screen Wristotle opens when launched via
     *  the system Quick Launch button. Int32 enum: 0 = dictation (default),
     *  1 = notes. Matches the QuickLaunchAction enum in the watch's config.h. */
    val SETTING_QUICK_LAUNCH_ACTION: UInt      = 10031u

    /** Quick Launch action wire values. Stable; persisted on the watch. */
    const val QUICK_LAUNCH_ACTION_DICTATE: Int = 0
    const val QUICK_LAUNCH_ACTION_NOTES: Int   = 1
    const val QUICK_LAUNCH_ACTION_MENU: Int    = 2

    /** Companion → watch: presence-only ping that asks the watch to ship back a
     *  snapshot containing every SETTING_* key + its current value. Added in
     *  watch app v0.X.Y; older watch apps ACK but don't respond, which the
     *  repository detects via a response timeout. */
    val REQUEST_SETTINGS: UInt   = 10026u

    /** Notes-on-watch (Phase C). Watch → companion: presence-only request that
     *  asks for the most recent notes. Companion → watch: a single CSTRING
     *  containing notes joined by [NOTES_SEPARATOR] (record separator); each
     *  note is the body, truncated to fit. */
    val NOTES_REQUEST: UInt      = 10027u
    val NOTES_RESPONSE: UInt     = 10028u

    /** Per-note detail fetch. Watch → companion: an Int32 with the note's
     *  index in the most-recent NOTES_RESPONSE (0..N-1). Companion → watch:
     *  the FULL body of that note, capped at [NOTE_DETAIL_MAX_CHARS] to fit
     *  one AppMessage. Used when the user drills into a row on the watch. */
    val NOTE_DETAIL_REQUEST: UInt  = 10029u
    val NOTE_DETAIL_RESPONSE: UInt = 10030u

    /** Cap on a single per-note detail body sent over [NOTE_DETAIL_RESPONSE].
     *  Stays under Pebble's AppMessage outbox budget (~636 bytes) minus
     *  tuple framing. */
    const val NOTE_DETAIL_MAX_CHARS: Int = 540

    /** Record-separator char (US-ASCII 0x1E) used to delimit notes inside a
     *  single NOTES_RESPONSE payload. Never appears in printable text so
     *  splitting is unambiguous. */
    const val NOTES_SEPARATOR: Char = ''

    /** All settings keys, grouped so [PebbleListenerService.onMessageReceived]
     *  can detect "this incoming message carries settings tuples" without a
     *  marker key. Any tuple of one of these keys is, by definition, a
     *  settings update from the watch. */
    val SETTING_KEYS: List<UInt> = listOf(
        SETTING_LOGGING,
        SETTING_DICTATION_CONFIRMATION,
        SETTING_FIND_PHONE_TARGET,
        SETTING_REMINDERS_TARGET,
        SETTING_CANCEL_TARGET,
        SETTING_QUICK_LAUNCH_AUTO_EXIT,
        SETTING_VIBRATE_ON_LAUNCH,
        SETTING_VIBRATE_ON_QUICK_LAUNCH,
        SETTING_VIBRATE_RESPECT_QUIET,
        SETTING_SKIP_RETRY_DIALOG,
        SETTING_QUICK_LAUNCH_ACTION,
    )

    /** Value of MSG_TARGET that means "this message is for the Android companion". */
    const val TARGET_COMPANION: Int = 1
}
