package com.lazydevs.wristotle.transport

/**
 * AppMessage key indices shared between the Pebble watch app and this companion.
 *
 * These values are auto-generated by the Pebble SDK from the `messageKeys` array
 * in the watch app's `package.json`. The source of truth is
 * `build/src/message_keys.auto.c` in the Wristotle watch app.
 */
object MessageKeys {
    val REMINDER_QUERY: UInt     = 10004u
    val REMINDER_RESULT: UInt    = 10005u
    val CANCEL_QUERY: UInt       = 10006u
    val CANCEL_RESULT: UInt      = 10007u
    val COMPANION_PING: UInt     = 10009u
    val COMPANION_READY: UInt    = 10010u
    val COMPANION_QUERY: UInt    = 10011u
    val COMPANION_RESPONSE: UInt = 10012u
    val MSG_TARGET: UInt         = 10014u

    /** Watch → companion logging payload (locally-handled commands the companion
     *  never sees through query channels). All three keys arrive in one message. */
    val LOG_QUERY: UInt          = 10023u
    val LOG_RESPONSE: UInt       = 10024u
    val LOG_HANDLER: UInt        = 10025u

    /** Value of MSG_TARGET that means "this message is for the Android companion". */
    const val TARGET_COMPANION: Int = 1
}
