// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2025-2026 Lazy Devs

package com.lazydevs.wristotle.ui

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.lazydevs.wristotle.WristotleApplication
import com.lazydevs.wristotle.speech.nlu.stats.Stats
import com.lazydevs.wristotle.speech.nlu.stats.StatsRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch

/**
 * Surface state for the Settings → 📊 Stats card.
 *
 * - [Loading] is the cold-start state. The card renders a skeleton
 *   row so the user knows the snapshot is being computed (snapshot
 *   wall-clock is ~50-150ms on a few-thousand-row conversation table).
 * - [Loaded] carries the immutable [Stats] snapshot the UI binds to.
 *
 * Refresh is explicit (via [StatsViewModel.refresh]) — the Stats card
 * isn't a live dashboard, so we don't subscribe to Flow updates from
 * every Room table. Compose's `LaunchedEffect` triggers a refresh on
 * screen open.
 */
sealed interface StatsUiState {
    object Loading : StatsUiState
    data class Loaded(val stats: Stats) : StatsUiState
}

class StatsViewModel(app: Application) : AndroidViewModel(app) {

    private val repository: StatsRepository = StatsRepository(
        source = (app as WristotleApplication).statsSource,
        now = System::currentTimeMillis,
    )

    private val _state = MutableStateFlow<StatsUiState>(StatsUiState.Loading)
    val state: StateFlow<StatsUiState> = _state

    init { refresh() }

    /** Snapshot the underlying stores into a fresh [Stats]. Called on
     *  init and again from the UI's `LaunchedEffect` when the user
     *  re-enters the screen (so data the user just generated by
     *  speaking to the watch shows up immediately on return). */
    fun refresh() {
        viewModelScope.launch {
            val snapshot = repository.snapshot()
            _state.value = StatsUiState.Loaded(snapshot)
        }
    }
}
